play_suggested:
  description: Play the suggested episode
  fields:
    program_name:
      description: The name of the SVT program.
      example: "rapport"
    entity_id:
      description: Name(s) of entities to play on.
      example: "media_player.living_room_chromecast"
    formats:
      description: List of video formats to try, in order of preference.
      example: ["hls", "dash"]
play_latest:
  description: Play the latest episode
  fields:
    program_name:
      description: The name of the SVT program.
      example: "rapport"
    entity_id:
      description: Name(s) of entities to play on.
      example: "media_player.living_room_chromecast"
    category:
      description: Name(s) of categories that should be used.
      example: "Klipp"
    exclude_category:
      description: Name(s) of categories that shouldn't be used.
      example: "utan filmer"
    formats:
      description: List of video formats to try, in order of preference.
      example: ["hls", "dash"]
play_channel:
  description: Play the a specified channel
  fields:
    channel:
      description: The name of the channel.
      example: "svt1"
    entity_id:
      description: Name(s) of entities to play on.
      example: "media_player.living_room_chromecast"
    formats:
      description: List of video formats to try, in order of preference.
      example: ["hls", "dash"]
play_videoid:
  description: Play the specified video id
  fields:
    videoid:
      description: The id of the video.
      example: "jXvZLoG"
    entity_id:
      description: Name(s) of entities to play on.
      example: "media_player.living_room_chromecast"
    formats:
      description: List of video formats to try, in order of preference.
      example: ["hls", "dash"]
